/* ShadowBorn V20: carregamento por fase e HUD móvel personalizável. */
(()=>{'use strict';
const $=id=>document.getElementById(id),store='shadowborn_mobile_hud_v20',clamp=(x,a,b)=>Math.min(b,Math.max(a,x));
const defaults=()=>({mode:'analog',opacity:.9,buttons:{'touch-stick':{x:14,y:78,size:124},'touch-left':{x:9,y:81,size:66},'touch-right':{x:20,y:81,size:66},'touch-jump':{x:77,y:81,size:66},'touch-attack':{x:89,y:79,size:82},'touch-ultimate':{x:89,y:56,size:66}}});
let config=defaults(),draft=null,editing=false,selected='touch-stick',stickPointer=null;
try{const c=JSON.parse(localStorage.getItem(store));if(c){config.mode=c.mode==='arrows'?'arrows':'analog';config.opacity=clamp(Number(c.opacity)||.9,.35,1);for(const [id,v]of Object.entries(config.buttons)){const n=c.buttons?.[id];if(n&&[n.x,n.y,n.size].every(Number.isFinite))config.buttons[id]={x:clamp(n.x,0,100),y:clamp(n.y,0,100),size:clamp(n.size,44,180)};}}}catch{}
const current=()=>draft||config;
function resetInput(){resetKeys();stickPointer=null;$('touch-stick')?.style.setProperty('--stick-x','0px');$('touch-stick')?.style.setProperty('--stick-y','0px');document.querySelectorAll('.v20-pressed').forEach(e=>e.classList.remove('v20-pressed'));}
function apply(){const c=current(),host=$('mobile-controls');if(!host)return;host.dataset.mode=c.mode;host.style.setProperty('--hud-opacity',c.opacity);const r=$('game-wrapper').getBoundingClientRect();const scale=clamp(Math.min(r.width,r.height)/450,.7,1.4);for(const[id,v]of Object.entries(c.buttons)){const e=$(id);if(!e)continue;const size=Math.min(v.size*scale,Math.min(r.width,r.height)*.45);const edgeX=(size/2+8)/Math.max(1,r.width)*100,edgeY=(size/2+8)/Math.max(1,r.height)*100;e.style.width=size+'px';e.style.height=size+'px';e.style.left=clamp(v.x,edgeX,100-edgeX)+'%';e.style.top=clamp(v.y,edgeY,100-edgeY)+'%';e.classList.toggle('v20-selected',editing&&id===selected);}}
function select(id){selected=id;$('v20-hud-target').value=id;$('v20-hud-size').value=current().buttons[id].size;$('v20-hud-size-value').textContent=current().buttons[id].size+' px';apply();}
function editor(open,save=false){if(open){draft=structuredClone(config);editing=true;resetInput();$('v20-hud-editor').hidden=false;$('game-wrapper').classList.add('v20-hud-editing');$('v20-hud-mode').value=draft.mode;$('v20-hud-opacity').value=Math.round(draft.opacity*100);select(draft.mode==='analog'?'touch-stick':'touch-left');apply();return;}if(save){try{localStorage.setItem(store,JSON.stringify(draft));config=structuredClone(draft);}catch{$('v20-hud-note').textContent='Não foi possível salvar no aparelho. Libere o armazenamento e tente novamente.';return;}}draft=null;editing=false;resetInput();$('v20-hud-editor').hidden=true;$('game-wrapper').classList.remove('v20-hud-editing');apply();}
function bindDrag(el){let drag=null;el.addEventListener('pointerdown',e=>{if(!editing)return;e.preventDefault();e.stopImmediatePropagation();select(el.id);const r=el.getBoundingClientRect();drag={id:e.pointerId,dx:e.clientX-(r.left+r.width/2),dy:e.clientY-(r.top+r.height/2)};el.setPointerCapture(e.pointerId);},true);el.addEventListener('pointermove',e=>{if(!editing||drag?.id!==e.pointerId)return;const r=$('mobile-controls').getBoundingClientRect(),v=draft.buttons[el.id];v.x=clamp((e.clientX-drag.dx-r.left)/r.width*100,0,100);v.y=clamp((e.clientY-drag.dy-r.top)/r.height*100,0,100);apply();});const end=e=>{if(drag?.id===e.pointerId)drag=null;};el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);el.addEventListener('lostpointercapture',end);}
function stickMove(e){if(stickPointer!==e.pointerId)return;const el=$('touch-stick'),r=el.getBoundingClientRect(),radius=r.width*.3,dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),dist=Math.hypot(dx,dy),f=dist>radius?radius/dist:1;el.style.setProperty('--stick-x',dx*f+'px');el.style.setProperty('--stick-y',dy*f+'px');const direction=dx<-radius*.22?-1:dx>radius*.22?1:0;keys.a.pressed=direction===-1;keys.d.pressed=direction===1;if(direction)player.lastKeyPressed=direction<0?'a':'d';}
function prepareLoading(phase){const bg=$('v20-loading-bg'),screen=$('loading-screen');$('v20-loading-map').textContent=phase.name||'Mapa';bg.hidden=phase.bgType==='gradient';screen.style.background=phase.bgType==='gradient'?'linear-gradient('+String(phase.bgColors?.top||'#21152c')+','+String(phase.bgColors?.bottom||'#050607')+')':'#090a0e';if(!bg.hidden)bg.src=phase.bgValue||ASSET_PATHS.background;bg.onerror=()=>{bg.hidden=true;};$('v9-loadfill').style.width='0%';$('v9-loadpct').textContent='0%';}
function build(){
 const host=$('mobile-controls');host.classList.add('v20-controls');for(const name of ['left','right','jump','attack','ultimate']){const e=$('touch-'+name);e.innerHTML='<img src="./assets/ui-v20/hud-'+name+'.svg" alt="" draggable="false">';e.classList.add('v20-control');host.appendChild(e);}
 host.querySelector('.touch-dpad')?.remove();host.querySelector('.touch-actions')?.remove();const stick=document.createElement('div');stick.id='touch-stick';stick.className='v20-control v20-stick';stick.setAttribute('role','group');stick.setAttribute('aria-label','Analógico de movimento');stick.innerHTML='<span class="v20-stick-ring"></span><span class="v20-stick-thumb"></span>';host.appendChild(stick);
 const panel=document.createElement('section');panel.className='v20-settings';panel.innerHTML='<h3>HUD mobile</h3><p>Escolha analógico ou setas. Arraste cada botão e ajuste o tamanho no editor.</p><button id="v20-open-editor" class="v19-primary">PERSONALIZAR CONTROLES</button><small>Configuração salva neste aparelho. O teclado do PC continua disponível.</small>';$('system-screen').firstElementChild.querySelector('.v8-back').before(panel);
 const overlay=document.createElement('section');overlay.id='v20-hud-editor';overlay.hidden=true;overlay.innerHTML='<div class="v20-hud-toolbar"><h3>AJUSTAR HUD</h3><label>Movimento<select id="v20-hud-mode"><option value="analog">Analógico</option><option value="arrows">Setas</option></select></label><label>Botão<select id="v20-hud-target"><option value="touch-stick">Analógico</option><option value="touch-left">Esquerda</option><option value="touch-right">Direita</option><option value="touch-jump">Pulo</option><option value="touch-attack">Ataque</option><option value="touch-ultimate">Ultimate</option></select></label><label>Tamanho <b id="v20-hud-size-value"></b><input id="v20-hud-size" type="range" min="44" max="180" value="66"></label><label>Opacidade<input id="v20-hud-opacity" type="range" min="35" max="100" value="90"></label><div><button id="v20-hud-reset">Restaurar</button><button id="v20-hud-cancel">Cancelar</button><button id="v20-hud-save">SALVAR</button></div><p id="v20-hud-note">Arraste os botões na tela. Use o celular na horizontal para jogar.</p></div>';$('game-wrapper').appendChild(overlay);
 const pauseEdit=document.createElement('button');pauseEdit.id='v20-pause-hud';pauseEdit.className='btn btn-secondary';pauseEdit.textContent='Personalizar HUD';$('shop-btn-pause').after(pauseEdit);pauseEdit.onclick=()=>editor(true);$('v20-open-editor').onclick=()=>editor(true);$('v20-hud-save').onclick=()=>editor(false,true);$('v20-hud-cancel').onclick=()=>editor(false);$('v20-hud-reset').onclick=()=>{draft=defaults();$('v20-hud-mode').value=draft.mode;$('v20-hud-opacity').value=draft.opacity*100;select('touch-stick');apply();};$('v20-hud-mode').onchange=e=>{draft.mode=e.target.value;select(draft.mode==='analog'?'touch-stick':'touch-left');};$('v20-hud-target').onchange=e=>{if(e.target.value==='touch-stick'){draft.mode='analog';}else if(['touch-left','touch-right'].includes(e.target.value)){draft.mode='arrows';}$('v20-hud-mode').value=draft.mode;select(e.target.value);};$('v20-hud-size').oninput=e=>{draft.buttons[selected].size=Number(e.target.value);$('v20-hud-size-value').textContent=e.target.value+' px';apply();};$('v20-hud-opacity').oninput=e=>{draft.opacity=Number(e.target.value)/100;apply();};host.querySelectorAll('.v20-control').forEach(bindDrag);
 stick.addEventListener('pointerdown',e=>{if(editing||gameState!=='playing'||stickPointer!==null)return;e.preventDefault();stickPointer=e.pointerId;stick.setPointerCapture(e.pointerId);stickMove(e);});stick.addEventListener('pointermove',stickMove);const stop=e=>{if(stickPointer!==e.pointerId)return;stickPointer=null;keys.a.pressed=keys.d.pressed=false;stick.style.setProperty('--stick-x','0px');stick.style.setProperty('--stick-y','0px');};for(const ev of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(ev,stop);
 window.addEventListener('blur',resetInput);document.addEventListener('visibilitychange',()=>{if(document.hidden)resetInput();});new MutationObserver(()=>{if(gameState!=='playing')resetInput();}).observe(host,{attributes:true,attributeFilter:['class']});new ResizeObserver(apply).observe($('game-wrapper'));apply();
}
window.ShadowHUD={prepareLoading,openEditor:()=>editor(true),get editing(){return editing;},getConfig:()=>structuredClone(config)};document.addEventListener('DOMContentLoaded',build);
})();
